Feature/action queue system
Sweaty-Bacon-Ducks/DigThemGraves pull request #11
Opened 2019-08-09 11:55 UTC by Kodeman010

Dodano system kolejkowania rozkazów, oraz ich wyświetlanie z możliwością anulowania.

2019-08-09 12:00 UTC, Kodeman010 commented on Assets/Scripts/Actions/ActionQueue.cs
> +                currentAction = null;
Zostawiłem tak mimo ostrzeżeń, by nie przypisywać do null. Inaczej pojawiają się problemy z wykonywaniem akcji. Poza tym, wydaje mi się, że w tym przypadku pasuje, gdyż jak nie ma akcji, to powinno być puste (null).

2019-08-11 14:35 UTC, copy-on-meow requested changes

2019-08-11 14:35 UTC, copy-on-meow commented on Assets/Scripts/Actions/ActionDisplay.cs
> +    public class ActionDisplay : MonoBehaviour
`ActionView` jest lepszą nazwą

2019-08-11 16:57 UTC, KowalikJakub commented
Proszę o rozwiązanie #15

2019-08-23 10:29 UTC, KowalikJakub commented
ref. #11

2019-08-23 10:33 UTC, copy-on-meow requested changes
Blocked by #15

2019-09-06 20:01 UTC, copy-on-meow requested changes

2019-09-06 20:01 UTC, copy-on-meow commented on Assets/Scripts/Actions/ActionView.cs
> +            ActionQueue actionQueue = GameObject.FindGameObjectWithTag("GameManager").GetComponent<ActionQueue>();
Wolałbym to jako pole w tej klasie a nie szukanie po tagach. Poza tym spoko

2019-09-06 20:01 UTC, copy-on-meow commented on Assets/Scripts/BuildSlot.cs
> +        public abstract void OnMouseUp();
Chyba nie musisz tego pisać, bo to jest jako callback w MonoBehaviour, więc wszystkie klasy dziedziczące po `BuildSlot` będą to miały możliwość przesłonięcia tej metody

2019-09-06 20:01 UTC, copy-on-meow commented on Assets/Scripts/Core/IAction.cs
> +        Sprite Sprite { get; set; }
A to przypadkiem nie jest elementem widoku poszczególnej akcji? Wydaje mi się że to należy wywalić do klasy zajmującej się widokiem

2019-09-06 20:01 UTC, KowalikJakub commented on Assets/Scripts/ScriptablePlayerAction.cs
> +        public void Cancel()
Wydaje mi się że zapomniałeś o `abstract`

2019-09-11 14:35 UTC, copy-on-meow approved these changes

2019-09-11 14:36 UTC, merged